---
kind: pipeline
name: default

steps:
- name: build
  image: debian:bookworm
  commands:
    - apt-get update
    - apt-get install -yy --no-install-recommends g++ make qtbase5-dev libkf5kio-dev
    - cd src/ && qmake && make

- name: test
  image: debian:bookworm
  commands:
    - apt-get update
    - apt-get install -yy --no-install-recommends kio libkf5kiofilewidgets5 python3
    - python3 -m unittest discover test/ -v
